Add clifm to the list of truecolor programs
termstandard/colors pull request #60
Opened 2024-09-26 19:52 UTC by leo-arch

As the title says, add [clifm](https://github.com/leo-arch/clifm) to the list of programs supporting truecolor.

2025-05-03 17:25 UTC, BridgeAR requested changes
Looking at their documentation, it says it will default to either 256 or 16 colors, depending on color support being detected or not. It also seems it is possible to enforce color support with some environment variables but that's not the default and I would not list as regularly supporting true color.

2025-05-03 17:35 UTC, leo-arch commented
Hi @BridgeAR. Though **clifm** runs  by default in either 256 or 16  colors (for compatibility reasons), it does [support truecolors](https://github.com/leo-arch/clifm/wiki/Customization#supported-colors) in that it provides truecolor [color schemes](https://github.com/leo-arch/clifm/tree/master/misc/colors), for example, [molokai](https://github.com/leo-arch/clifm/blob/master/misc/colors/molokai.clifm) or [gruvbox](https://github.com/leo-arch/clifm/blob/master/misc/colors/gruvbox.clifm).

2025-05-17 04:13 UTC, kurahaupo commented
Good patch, but please keep the list in alphabetical order

2025-05-18 06:34 UTC, kurahaupo approved these changes

2025-06-04 03:19 UTC, merged